theme: jekyll-theme-hacker
title: ZeroYaHero
description: Games, tools, shaders, and renders.
show_downloads: false

email: zeroyaheroofficial@gmail.com
github_url: https://github.com/ZeroYaHero
twitter_url: https://x.com/ZeroYaHero

exclude:
  - README.md
